Document: visionsgs
Title: Debian visionsgs Manual
Author: <insert document author here>
Abstract: This manual describes what visionsgs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/visionsgs/visionsgs.sgml.gz

Format: postscript
Files: /usr/share/doc/visionsgs/visionsgs.ps.gz

Format: text
Files: /usr/share/doc/visionsgs/visionsgs.text.gz

Format: HTML
Index: /usr/share/doc/visionsgs/html/index.html
Files: /usr/share/doc/visionsgs/html/*.html
